- hosts: git_nodes
  become: yes
  vars:
   destination: ~/ec2-user
  tasks:
    - name: "install git"
      yum:
        name: git
        state: latest
    - name: "install python"
      yum:
        name: python
        state: latest
    - name: "clone repo with python code"
      git:
        repo: 'https://github.com/jkanclerz/google-search-python.git'
        dest: "{{destination}}"
        clone: no
        update: yes
    - name: "clone repo with scripts"
      git:
        repo: 'https://github.com/jkanclerz/install-image-me.git'
        dest: "{{destination}}"
        clone: no
        update: yes